server:
  port: 9003
spring:
  application:
    name: ECOMMERCE-SERVICE
  profiles:
    active: db,mongo,server
  config:
    import:
      - "optional:configserver:http://localhost:9009"

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: cart
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    topic:
      name: cart-topic


